version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: nest_postgres_management
    restart: always
    environment:
      POSTGRES_USER: anil
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nest_app_management
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
